on:
  schedule:
    - cron: '6,9,13,19,26,32,39,42,45,52,58 * * * *'  # runs at fixed minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping endpoint
        run: curl -sf https://codercat-server.onrender.com/ping && echo "✅ pong"
