on:
  schedule:
    - cron: '*/2 * * * *'  # every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Random chance to ping
        id: choice
        run: |
          CHANCE=$((RANDOM % 5))
          echo "chance=$CHANCE" >> $GITHUB_OUTPUT

      - name: Ping endpoint
        if: steps.choice.outputs.chance == '0'
        run: curl -sf https://codercat-server.onrender.com/ping && echo "✅ pong"
